feat: dutch translation
XiaoMi/ha_xiaomi_home pull request #168
Opened 2024-12-18 13:06 UTC by wheresrofl

2024-12-18 13:11 UTC, SusanPhevos requested changes
Can you also add custom_components/xiaomi_home/miot/i18n/nl.json ？

2024-12-18 17:06 UTC, wheresrofl commented
sorry about that, didn't even see the file. updated now

2024-12-18 19:05 UTC, JimmyKmi approved these changes

2024-12-19 06:07 UTC, SusanPhevos approved these changes

2024-12-19 06:07 UTC, merged